
import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLJPanel;
import com.jogamp.opengl.util.FPSAnimator;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author karma
 */
public class JavaSpriteViewer extends javax.swing.JFrame {

	
	/**
	 * Creates new gui
	 * @param args cmd line arguments as a string array
	 */
	public JavaSpriteViewer(String[] args) {
		initComponents();
		
		//set input image to argument 0
		if (args.length > 0) {
			
			try {
				File f = new File(args[0]);
				BufferedImage img = ImageIO.read(f);
				optionsPanel1.jImagePanel1.setImage(img.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
				optionsPanel1.jImagePanel1.paintComponent(optionsPanel1.jImagePanel1.getGraphics());
				optionsPanel1.setFileName(args[0]);
				
			} catch (IOException ex) {
				
				String s = "error opening" + args[0];
				JOptionPane.showMessageDialog(rootPane, s);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                optionsPanel1 = new OptionsPanel();
                //OpenGL panel
                GLProfile glprofile = GLProfile.get("GL3");
                GLCapabilities glcapabilities = new GLCapabilities(glprofile);
                gLJPanel1 = new GLJPanel(glcapabilities);
                Renderer rend = new Renderer(optionsPanel1);
                gLJPanel1.addGLEventListener(rend);
                optionsPanel1.setRenderer(rend);
                FPSAnimator ani = new FPSAnimator(gLJPanel1, 60);
                ani.start();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Java Sprite Viewer");
                getContentPane().add(optionsPanel1, java.awt.BorderLayout.WEST);

                gLJPanel1.setPreferredSize(new java.awt.Dimension(512, 512));

                javax.swing.GroupLayout gLJPanel1Layout = new javax.swing.GroupLayout(gLJPanel1);
                gLJPanel1.setLayout(gLJPanel1Layout);
                gLJPanel1Layout.setHorizontalGroup(
                        gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 533, Short.MAX_VALUE)
                );
                gLJPanel1Layout.setVerticalGroup(
                        gLJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 543, Short.MAX_VALUE)
                );

                getContentPane().add(gLJPanel1, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JavaSpriteViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JavaSpriteViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JavaSpriteViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JavaSpriteViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JavaSpriteViewer(args).setVisible(true);
			}
		});
		
		
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private com.jogamp.opengl.awt.GLJPanel gLJPanel1;
        public OptionsPanel optionsPanel1;
        // End of variables declaration//GEN-END:variables
}
